#! /usr/bin/python3

import os
import re
import sys
import logging
import argparse
import subprocess
from mega import Mega

logging.basicConfig(level=logging.INFO)

parse = argparse.ArgumentParser(description='Mega to Drive Transfer Script',
                                usage='smegma -url "https://mega.blah"' + \
                                      '-tool _clone ' + \
                                      '-upload "remote:/path"' + \
                                      '\nUse "smegma -h" for help',
                                epilog='Script by @firstwastaken')

parse.add_argument('-url',
                    metavar='https://mega.blah',
                    type=str,
                    help='mega public url',
                    required=True)

parse.add_argument('-upload',
                    metavar='remote:/path',
                    type=str,
                    help='clone upload path with remote name',
                    required=True)

parse.add_argument('-login',
                    metavar='email:password',
                    type=str,
                    help='If specified, instead of using a temp account it ' + \
                         'uses your account')

parse.add_argument('-tool',
                    metavar='g/f/rclone',
                    type=str,
                    help='Name of the clonetool you are gonna use : ' + \
                         'rclone, gclone, fclone',
                    required=True)

mega = Mega()
args = parse.parse_args()

pwd = os.environ.get("PWD")
dir_ = f"{pwd}/mega/"

def clone(command):
    with subprocess.Popen(
            args.tool + command,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            shell=True) as proc:
        print('Uploading...')
        for line in iter(proc.stdout.readline, b''):
            line = str(line).replace("b'", '').replace("\\n'", '')
            if line != '':
                sys.stdout.write('\r' + line)
                sys.stdout.flush()
        print('\nDone!')

def dwld_to_dir():
    os.chdir(dir_); dl_prefix.download_url(args.url)

def upld_to_dir():
    print("Commencing upload...")
    clone(f" move {dir_} {args.upload} -v --stats=1s --stats-one-line")
        
if not args.login:
    dl_prefix = Mega().login()
elif args.login:
    if re.search(':', args.login):
        mail_id = args.login.split(':')[0]
        pass_ = args.login.split(':')[1]
        dl_prefix = Mega().login(mail_id, pass_)
    else:
        print("Please provide login details as email:password")
        sys.exit(1)

try:
    os.makedirs(dir_)
except FileExistsError:
    pass

try:
    dwld_to_dir()
except UnboundLocalError:
    print('ERROR: File too large/quota exceeded. ')
    if not args.login:
        print('Try logging in.')
    sys.exit(1)

upld_to_dir()
